### ISSUE TITLE
При подключении файла tools\ШаблоныКода.st видны не все строки, что есть в файле

### ISSUE THREAD

**Issue by antonsm2011** [Nivanchenko/formhelper#2]
Проверил на платформе 1С:Предприятие 8.3 (8.3.21.1484) и 1С:Предприятие 8.3 (8.3.23.1865).
![изображение](https://github.com/Nivanchenko/formhelper/assets/12731230/ce1a7b71-2e9e-4fdb-93ec-ce05c946d311)
Видно только 10 строк, хотя в файле их гораздо больше.

**Comment by Nivanchenko** [comment]
Привет. Поправил в https://github.com/Nivanchenko/formhelper/pull/3. Должно теперь отображаться корректно.

**Comment by antonsm2011** [comment]
Спасибо. Теперь полный список.
Я правильно понял, что самого генератора списка шаблонов в репозитории нет?
Или плохо искал?

**Comment by Nivanchenko** [comment]
> Спасибо. Теперь полный список. Я правильно понял, что самого генератора списка шаблонов в репозитории нет? Или плохо искал?

Верно, генератора нет. большая часть кода была взята из инструментов разработчика, которая умела читать платформенную справку, по ней сгенерили некоторые шаблоны. После генерации шаблоны еще доработались вручную. А причесывать код генератора, и доводить до полного автоматизма показалось избыточным. И там начинается тонкий лед в плане лицензии 1С на использование ее справки.
