### ISSUE TITLE
Добавить в таблицу на форме колонки

### ISSUE THREAD

**Issue by antonsm2011** [Nivanchenko/formhelper#9]
Есть реквизит формы ТаблицаЗначений с несколькими колонками.
Он выведен на форму как элемент формы ТаблицаЗначений .
Как через построитель добавить в них обоих еще колонок с разными типами?

**Comment by antonsm2011** [comment]
Или можно пример, как полностью создать через построитель реквизит ТаблицаЗначений  и соответствующий ему элемент формы ТаблицаЗначений?

**Comment by antonsm2011** [comment]
В статье на инфостарте (https://infostart.ru/1c/articles/1979960/) нашел такой пример:
![](https://infostart.ru/upload/iblock/cf7/cf7ca76fb99e63f0578fe19b43f1603c.jpg)

**Comment by Nivanchenko** [comment]
Привет. Есть вспомогательный плагин, который добавит табличку, по описанию, Описание можно сгенерить так же через экспортный метод общего модуля. 
Вот пример: 
```bsl
    Построитель = РаботаСФормамиСервер.НовыйПостроительФорм(ЭтаФорма);
    Построитель.ГруппаФормы("ГруппаСТаблицей");

    Описание = РаботаСФормамиСервер.ОписаниеТаблицы("ТаблицаНаФорме", "Таблица на форме", "ГруппаСТаблицей", Истина);

    Описание.Реквизиты.Добавить(
        РаботаСФормамиСервер.ОписаниеРеквизитаТаблицы("СтроковыйРеквизит", "Строковый реквизит", 
        Новый ОписаниеТипов("Строка",,Новый КвалификаторыСтроки(12))));
    
    Описание.Реквизиты.Добавить(
        РаботаСФормамиСервер.ОписаниеРеквизитаТаблицы("ЧисловойРеквизит", "Число", 
        Новый ОписаниеТипов("Число")));
													
   Построитель.Компоненты.Таблицы.РеквизитИЭлементФормыТаблицаПоОписанию(Описание)
```

Так же можно глянуть, что делает плагин по описанию, и сделать через билдер, но кода будет чуть больше.
